# Data Science Class - Date 3/26/2025

In [5]:
import pandas as pd

In [6]:
data = pd.read_csv("educ_figdp_1_Data.csv")

In [7]:
data.head()

,TIME,GEO,INDIC_ED,Value,Flag and Footnotes
0,2000,European Union (28 countries),Total public expenditure on education as % of ...,:,NaN
1,2001,European Union (28 countries),Total public expenditure on education as % of ...,:,NaN
2,2002,European Union (28 countries),Total public expenditure on education as % of ...,5.00,e
3,2003,European Union (28 countries),Total public expenditure on education as % of ...,5.03,e
4,2004,European Union (28 countries),Total public expenditure on education as % of ...,4.95,e

In [8]:
data.head(10)

,TIME,GEO,INDIC_ED,Value,Flag and Footnotes
0,2000,European Union (28 countries),Total public expenditure on education as % of ...,:,NaN
1,2001,European Union (28 countries),Total public expenditure on education as % of ...,:,NaN
2,2002,European Union (28 countries),Total public expenditure on education as % of ...,5.00,e
3,2003,European Union (28 countries),Total public expenditure on education as % of ...,5.03,e
4,2004,European Union (28 countries),Total public expenditure on education as % of ...,4.95,e
5,2005,European Union (28 countries),Total public expenditure on education as % of ...,4.92,e
6,2006,European Union (28 countries),Total public expenditure on education as % of ...,4.91,e
7,2007,European Union (28 countries),Total public expenditure on education as % of ...,4.92,e
8,2008,European Union (28 countries),Total public expenditure on education as % of ...,5.04,e
9,2009,European Union (28 countries),Total public expenditure on education as % of ...,5.38,e

In [9]:
data.tail()

,TIME,GEO,INDIC_ED,Value,Flag and Footnotes
379,2007,Finland,Total public expenditure on education as % of ...,5.90,NaN
380,2008,Finland,Total public expenditure on education as % of ...,6.10,NaN
381,2009,Finland,Total public expenditure on education as % of ...,6.81,NaN
382,2010,Finland,Total public expenditure on education as % of ...,6.85,NaN
383,2011,Finland,Total public expenditure on education as % of ...,6.76,NaN

In [13]:
df = pd.read_csv("educ_figdp_1_Data.csv",
                 na_values = ":", usecols = ("TIME", "GEO", "Value"))

In [11]:
df.head()

   TIME                            GEO  Value
0  2000  European Union (28 countries)    NaN
1  2001  European Union (28 countries)    NaN
2  2002  European Union (28 countries)   5.00
3  2003  European Union (28 countries)   5.03
4  2004  European Union (28 countries)   4.95

In [12]:
data.describe()

              TIME
count   384.000000
mean   2005.500000
std       3.456556
min    2000.000000
25%    2002.750000
50%    2005.500000
75%    2008.250000
max    2011.000000