# Data Science Class - Date 3/26/2025

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("educ_figdp_1_Data.csv")

In [4]:
data.head()

,TIME,GEO,INDIC_ED,Value,Flag and Footnotes
0,2000,European Union (28 countries),Total public expenditure on education as % of ...,:,NaN
1,2001,European Union (28 countries),Total public expenditure on education as % of ...,:,NaN
2,2002,European Union (28 countries),Total public expenditure on education as % of ...,5.00,e
3,2003,European Union (28 countries),Total public expenditure on education as % of ...,5.03,e
4,2004,European Union (28 countries),Total public expenditure on education as % of ...,4.95,e

In [5]:
data.tail()

,TIME,GEO,INDIC_ED,Value,Flag and Footnotes
379,2007,Finland,Total public expenditure on education as % of ...,5.90,NaN
380,2008,Finland,Total public expenditure on education as % of ...,6.10,NaN
381,2009,Finland,Total public expenditure on education as % of ...,6.81,NaN
382,2010,Finland,Total public expenditure on education as % of ...,6.85,NaN
383,2011,Finland,Total public expenditure on education as % of ...,6.76,NaN

In [6]:
df = pd.read_csv("educ_figdp_1_Data.csv", na_values=':', usecols=['TIME', "GEO", "Value"])

In [7]:
df.describe()

              TIME       Value
count   384.000000  361.000000
mean   2005.500000    5.203989
std       3.456556    1.021694
min    2000.000000    2.880000
25%    2002.750000    4.620000
50%    2005.500000    5.060000
75%    2008.250000    5.660000
max    2011.000000    8.810000

In [8]:
df.head()

   TIME                            GEO  Value
0  2000  European Union (28 countries)    NaN
1  2001  European Union (28 countries)    NaN
2  2002  European Union (28 countries)   5.00
3  2003  European Union (28 countries)   5.03
4  2004  European Union (28 countries)   4.95

In [9]:
df.tail()

     TIME      GEO  Value
379  2007  Finland   5.90
380  2008  Finland   6.10
381  2009  Finland   6.81
382  2010  Finland   6.85
383  2011  Finland   6.76

In [10]:
df['Value']

0       NaN
1       NaN
2      5.00
3      5.03
4      4.95
       ...
379    5.90
380    6.10
381    6.81
382    6.85
383    6.76
Name: Value, Length: 384, dtype: float64

In [11]:
df.Value

0       NaN
1       NaN
2      5.00
3      5.03
4      4.95
       ...
379    5.90
380    6.10
381    6.81
382    6.85
383    6.76
Name: Value, Length: 384, dtype: float64

In [12]:
df[10:14]

    TIME                            GEO  Value
10  2010  European Union (28 countries)   5.41
11  2011  European Union (28 countries)   5.25
12  2000  European Union (27 countries)   4.91
13  2001  European Union (27 countries)   4.99

In [13]:
df.loc[90:94, ['TIME', 'GEO']]

    TIME      GEO
90  2006  Belgium
91  2007  Belgium
92  2008  Belgium
93  2009  Belgium
94  2010  Belgium

In [14]:
df.iloc[90:94, [0,1]]

    TIME      GEO
90  2006  Belgium
91  2007  Belgium
92  2008  Belgium
93  2009  Belgium

In [15]:
#df_filter = df['Value'].where(df['Value'] > 6.5, other=0).tail()
#df_filter

df['Value'].where(df['Value'] > 6.5, other=0).tail()

379    0.00
380    0.00
381    6.81
382    6.85
383    6.76
Name: Value, dtype: float64

In [16]:
df[df['Value'].isnull()].head()

    TIME                            GEO  Value
0   2000  European Union (28 countries)    NaN
1   2001  European Union (28 countries)    NaN
36  2000       Euro area (18 countries)    NaN
37  2001       Euro area (18 countries)    NaN
48  2000       Euro area (17 countries)    NaN

In [17]:
df.max(axis = 0)

TIME      2011
GEO      Spain
Value     8.81
dtype: object

In [18]:
df[["TIME","Value","GEO"]].max()

TIME      2011
Value     8.81
GEO      Spain
dtype: object

In [19]:
print("Pandas max function :\n", df['Value'].max(axis=0))

Pandas max function :
 8.81

In [20]:
print("Python max function :\n", max(df['Value']))

Python max function :
 nan

In [21]:
df_math = df['Value'] / 100
df_math.head()

0       NaN
1       NaN
2    0.0500
3    0.0503
4    0.0495
Name: Value, dtype: float64

In [22]:
import numpy as np
df_math1 = df['Value'].apply(np.sqrt)
df_math1.head()

0         NaN
1         NaN
2    2.236068
3    2.242766
4    2.224860
Name: Value, dtype: float64

In [23]:
import numpy as np
df_math1 = df['Value'].apply(lambda d: d**2)
df_math1.head()

0        NaN
1        NaN
2    25.0000
3    25.3009
4    24.5025
Name: Value, dtype: float64

In [24]:
df["ValueNorm"] = df["Value"]/df["Value"].max()
df.tail()

     TIME      GEO  Value  ValueNorm
379  2007  Finland   5.90   0.669694
380  2008  Finland   6.10   0.692395
381  2009  Finland   6.81   0.772985
382  2010  Finland   6.85   0.777526
383  2011  Finland   6.76   0.767310