# Gdp Analysis

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("educ_figdp_1_Data.csv")

In [3]:
data.head()

,TIME,GEO,INDIC_ED,Value,Flag and Footnotes
0,2000,European Union (28 countries),Total public expenditure on education as % of ...,:,NaN
1,2001,European Union (28 countries),Total public expenditure on education as % of ...,:,NaN
2,2002,European Union (28 countries),Total public expenditure on education as % of ...,5.00,e
3,2003,European Union (28 countries),Total public expenditure on education as % of ...,5.03,e
4,2004,European Union (28 countries),Total public expenditure on education as % of ...,4.95,e

In [4]:
data.tail()

,TIME,GEO,INDIC_ED,Value,Flag and Footnotes
379,2007,Finland,Total public expenditure on education as % of ...,5.90,NaN
380,2008,Finland,Total public expenditure on education as % of ...,6.10,NaN
381,2009,Finland,Total public expenditure on education as % of ...,6.81,NaN
382,2010,Finland,Total public expenditure on education as % of ...,6.85,NaN
383,2011,Finland,Total public expenditure on education as % of ...,6.76,NaN

In [5]:
df= pd.read_csv("educ_figdp_1_Data.csv", na_values=":", usecols=["TIME", "GEO", "Value"])

In [6]:
df.head()

   TIME                            GEO  Value
0  2000  European Union (28 countries)    NaN
1  2001  European Union (28 countries)    NaN
2  2002  European Union (28 countries)   5.00
3  2003  European Union (28 countries)   5.03
4  2004  European Union (28 countries)   4.95

In [7]:
df.describe()

              TIME       Value
count   384.000000  361.000000
mean   2005.500000    5.203989
std       3.456556    1.021694
min    2000.000000    2.880000
25%    2002.750000    4.620000
50%    2005.500000    5.060000
75%    2008.250000    5.660000
max    2011.000000    8.810000

In [8]:
df.GEO

0      European Union (28 countries)
1      European Union (28 countries)
2      European Union (28 countries)
3      European Union (28 countries)
4      European Union (28 countries)
                   ...
379                          Finland
380                          Finland
381                          Finland
382                          Finland
383                          Finland
Name: GEO, Length: 384, dtype: object

In [9]:
df["GEO"]

0      European Union (28 countries)
1      European Union (28 countries)
2      European Union (28 countries)
3      European Union (28 countries)
4      European Union (28 countries)
                   ...
379                          Finland
380                          Finland
381                          Finland
382                          Finland
383                          Finland
Name: GEO, Length: 384, dtype: object

In [10]:
df.Value

0       NaN
1       NaN
2      5.00
3      5.03
4      4.95
       ...
379    5.90
380    6.10
381    6.81
382    6.85
383    6.76
Name: Value, Length: 384, dtype: float64

In [11]:
df["TIME"]

0      2000
1      2001
2      2002
3      2003
4      2004
       ...
379    2007
380    2008
381    2009
382    2010
383    2011
Name: TIME, Length: 384, dtype: int64

In [12]:
df.GEO[10:19]

10    European Union (28 countries)
11    European Union (28 countries)
12    European Union (27 countries)
13    European Union (27 countries)
14    European Union (27 countries)
15    European Union (27 countries)
16    European Union (27 countries)
17    European Union (27 countries)
18    European Union (27 countries)
Name: GEO, dtype: object

In [13]:
first_name= "robin"
age= 11

In [14]:
print(first_name)

robin

In [15]:
print(first_name, "is a boy")

robin is a boy

In [16]:
age = age + 3
print('Age in three years:', age)

Age in three years: 14

In [17]:
print(first_name[0])

r